layout_spectrum: 0.2258064
typography_spectrum: 0.1067877
color:
  saturation: 0.8366126
  brandStrength: 0.9835593
  lightness: 0.8553432
  brandColors:
    - '#000000'
    - '#FFFFFF'
    - '#E0E0E0'
    - '#393939'
    - '#A3A3A3'
  rhythmicContrast: 0.2636478
name: 'Open Queue '
