typography_spectrum: 0.1067877
color:
  saturation: 0.8366126
  brandStrength: 0.9835593
  lightness: 0.8553432
  brandColors:
    - '#000000'
    - '#FFFFFF'
    - '#E0E0E0'
    - '#393939'
    - '#A3A3A3'
  rhythmicContrast: 0.2636478
layout_spectrum: 0.2258064
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/005cb5fa-e46a-407f-9536-2c80469c97aa.jpg
name: Open Queue Productions
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a81ada10-48c1-493a-a530-eb02128824c7.jpg
title: "About \_Us"
